[map]
raw = '''
 G
 G---- G----
 | W | |   |
 | | | |W  |
 |   | |   |
 |---| |---|

 G---- G----
 |  W| |   |
 |  || | W |
 |   | | | |
 |---| |---|
x            
'''

[info]
author = "w"
title = "Moving Forest"
