[map]
raw = '''
W~~~~~~~~~~~~~~~~
|               |
|     B   B     |
|     W   W     |
| G          xRx|
|     W   W     |
|     B   B     |
|               |
|~~~~~~~~~~~~~~~|'''

[info]
author = "w"
title = "A Moth to Flame"
