[map]
raw = '''W~~~~~~~~~~~~~~~~~~~~
|                   |
| R R               |
|        R      B   |
| B B B    B B R R  |
|  R   B R  B   B   |
|  |                |
| B B  R G B~ B     |
| |     B  | R      |
|          |        |
|          |~ R     |
| x                 |
|~~~~~~~~~~~~~~~~~~~~'''

[[map.commands]]
binding = [[9, 5], [12, 5], [16, 5], [7, 5], [8, 8], [13, 8]]
content = "U"
looping = true

[[map.commands]]
binding = [[9, 3], [16, 3], [3, 5]]
content = "D"
looping = true

[[map.commands]]
binding = [[4, 2], [4, 4], [4, 7], [13, 4], [17, 4], [9, 7], [14, 7], [14, 7], [14, 10]]
content = "L"
looping = true

[[map.commands]]
binding = [[2, 2], [2, 4], [6, 4], [11, 4], [15, 4], [2, 7], [7, 7], [11, 7]]
content = "R"
looping = true

[info]
author = "w"
title = "Experiment"
