[map]
raw = '''
W-  R-
||  ||
G-  R-          xx
||  ||          xx
G-  R-
||  ||
'''

[[map.commands]]
binding = [[4, 0], [4, 2], [4, 4]]
content = "R10I2L10I2"
looping = true

[info]
author = "w"
title = "Experiment"
