directory = 'level'
extension = 'toml'
name_list = [
  'experiment',
  'introduction',
  'a_moth_to_flame',
  'detour',
  'tetris',
  'swap',
  'matrix',
  'haircut',
  'printer',
  'centrosymmetry_and_axisymmetry',
  'sacrifice',
]
