directory = 'level'
extension = 'toml'
name_list = [
  # 'debug',
  # 'experiment',
  # 'unlock',
  'introduction',
  'a_moth_to_flame',
  'detour',
  'tetris',
  'swap',
  'matrix',
  'haircut',
  'printer',
  'centrosymmetry_and_axisymmetry',
  'sacrifice',
  'reincarnation',
  'now_or_never',
]
