[map]
raw = '''
   x           GW
x             GW 
    x        GW  
            GW   
 x         GW    
          GW     
         GW      
        GW       
       GW        
      GW         
     GW          
    GW           
   GW            
  GW             
 GW              
GW               
W                '''

[info]
author = "w"
title = "Printer"
