[map]
raw = '''
W~~~~~~~~~~~
|   G      |
|   GG     |
|    G     |
|          |
|          |
|          |
|          |
|          |
|R~~~~  xR~|
||||||~xR/~|
|~~~~~~~~~~~'''

[[map.commands]]
binding = [[4, 1], [4, 2], [5, 2], [5, 3]]
content = "I3D1"
looping = true

[info]
author = "w"
title = "Crossover: Tetris"
