[map]
raw = '''

 RBG 
x
'''

[[map.commands]]
binding = [[1, 1]]
content = "UD"
looping = true

[[map.commands]]
binding = [[2, 1]]
content = "DU"
looping = true

[info]
author = "w"
title = "Debug Slap Again"
