directory = 'level'
extension = 'toml'
name_list = [
  # 'debug-slap',
  # 'debug-slap-2',
  # 'debug-circular-dependency',
  # 'debug-general',
  # 'experiment',
  'introduction',
  'a-moth-to-flame',
  'detour',
  'tetris',
  'moving-together',
  'haircut',
  'matrix',
  'moving-forest',
  'printer',
  'swap',
  'centrosymmetry-and-axisymmetry',
  'sacrifice',
  'reincarnation',
  'triangle-power',
  'synchronization',
  'now-or-never',
  'unlock',
]
