[map]
raw = '''
 WG      x  
 W---------W
x|        |G
 |        | 
 |  G     | 
 |        | 
 |        | 
 |     x  | 
 |        | 
G|        |x
W|--------- 
  x      GW 
'''

[[map.commands]]
binding = [[1, 0]]
content = "R"
looping = true

[[map.commands]]
binding = [[11, 1]]
content = "D"
looping = true

[[map.commands]]
binding = [[10, 11]]
content = "L"
looping = true

[[map.commands]]
binding = [[0, 10]]
content = "U"
looping = true

[info]
author = "w"
title = "Now or Never"
