[map]
raw = '''
G-    R-           x
||    ||
G-W-  R-
||||  ||
G-    R-
||    ||           x
'''

[[map.commands]]
binding = [[6, 0], [6, 2], [6, 4]]
content = "R10I2L10I2"
looping = true

[info]
author = "w"
title = "Triangle Power"
