[map]
raw = '''
G---------

 W      W
 |      |G
 |WWWWWW|
 ||||||||G
xW|||W||W
 |W|W||W|G
 ||W||W||
 ||||||||G
 ||||||||
x|------/G
'''

[[map.commands]]
binding = [[2, 4], [3, 4], [4, 4], [5, 4], [6, 4], [7, 4]]
content = "U2I2D2I4"
looping = true

[[map.commands]]
binding = [[2, 10], [3, 10], [4, 10], [5, 10], [6, 10], [7, 10]]
content = "U2LRD2I4"
looping = true

[[map.commands]]
binding = [[1, 6]]
content = "I2LRI6"
looping = true

[info]
author = "w"
title = "Unlock"
