[map]
raw = '''
G----------
| |        
|-|        
           
           
G          
 W--WWWWWWW
G||||||||||
 |xW|||W||W
G| |W|W||W|
 | ||W||W||
G| ||||||||
 | ||||||||
G|x|------/'''

[[map.commands]]
binding = [[4, 6], [5, 6], [6, 6], [7, 6], [8, 6], [9, 6]]
content = "U2I2D2I4"
looping = true

[[map.commands]]
binding = [[4, 12], [5, 12], [6, 12], [7, 12], [8, 12], [9, 12]]
content = "U2LRD2I4"
looping = true

[[map.commands]]
binding = [[3, 12]]
content = "I2LRI6"
looping = true

[info]
author = "w"
title = "Unlock"
