[package]
edition = "2021"
name = "cube-collection"
version = "0.3.0"

[dependencies]
# Local workspace
cube-core = {path = "../cube-core"}

# Bery and its plugins
bevy = "0.10.0"
bevy_prototype_lyon = "0.8"

# Extra utilities
serde = {version = "1.0", features = ["derive"]}
snafu = "0.7"
toml = "0.5"
